name: Docker CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # JDK
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 15
      # Chmod
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # Build
      - name: Build with Gradle
        run: ./gradlew validate
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: validate
    if: github.event_name == 'push'
    steps:
      - name: Deploy to CDN
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLUSTER_SSH_HOST }}
          username: ${{ secrets.CLUSTER_SSH_USER }}
          key: ${{ secrets.CLUSTER_SSH_KEY }}
          script: |
            cd /usr/share/nginx/lindsey/i18n
            git pull
